import { PARTS,STATIONS,NODES,freshState,maxEnergy,repCost,price,unlocked,level,reward,completeRep,buyNode,nextDay,restore,bodyShape,RepCycle } from './game.js';
import { GymScene } from './scene.js';
const $=id=>document.getElementById(id);
const paths={bench:'M3 17h18M5 17v4m14-4v4M6 13h11l3 4M4 4v6m16-6v6M2 7h20m-15 4 3 2 2-5',curl:'M3 7v10m3-12v14M18 5v14m3-12v10M6 12h12',squat:'M3 4v16M21 4v16M3 5h18M7 8h10m-5 0v6m0 0-4 5m4-5 4 5',heart:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z',target:'M20 12a8 8 0 1 1-8-8m0 8 9-9m-5 0h5v5M16 12a4 4 0 1 1-4-4',wind:'M3 8h12a3 3 0 1 0-3-3M3 12h16a3 3 0 1 1-3 3M3 16h6a3 3 0 1 1-3 3',bolt:'m13 2-9 12h7l-1 8 10-12h-8Z',weight:'M8 7V5a4 4 0 0 1 8 0v2M6 7h12l3 14H3Z',cycle:'M20 7a9 9 0 0 0-16 0m0-5v5h5M4 17a9 9 0 0 0 16 0m0 5v-5h-5',spark:'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3Z',sound:'m11 5-6 4H2v6h3l6 4Zm4 3a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14',mute:'m11 5-6 4H2v6h3l6 4Zm5 4 5 6m0-6-5 6'};
function icon(name){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.spark}"/></svg>`;}
const KEY='gym-club-save-v1';let state;try{state=restore(localStorage.getItem(KEY));}catch{state=freshState();}
let scene,active=null,walking=false,view='gym',toastTimer,exhaustTimer,pointer=null,startY=0,cycle=new RepCycle(),audio=null;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$('save-state').textContent='자동 저장';}catch{$('save-state').textContent='저장 불가';}}
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2500);}
function sound(kind='rep'){if(!state.sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const at=audio.currentTime;for(let i=0;i<2;i++){const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAt((kind==='buy'?620:380)*(1+i*.5),at+i*.07);g.gain.setValueAt(0,at+i*.07);g.gain.linearRampToValueAtTime(.055,at+i*.07+.008);g.gain.exponentialRampToValueAtTime(.001,at+i*.07+.15);o.connect(g);g.connect(audio.destination);o.start(at+i*.07);o.stop(at+i*.07+.17);}}catch{}}
function render(){
 $('day').textContent=String(state.day).padStart(2,'0');$('energy-text').textContent=`${state.energy} / ${maxEnergy(state)}`;$('energy-fill').style.width=`${state.energy/maxEnergy(state)*100}%`;$('energy-fill').style.background=state.energy<repCost(state)?'#d58a64':'#315b48';$('energy-note').textContent=state.energy<repCost(state)?'오늘은 충분히 했어요. 잠깐 쉬어가세요.':'운동할 때만 체력이 줄어듭니다';$('points').textContent=state.points.toLocaleString();$('tree-points').textContent=state.points.toLocaleString();$('today-total').textContent=Object.values(state.today).reduce((a,b)=>a+b,0)+'회';
 $('body-stats').innerHTML=Object.entries(PARTS).map(([id,p])=>`<div class="body-row"><div><span>${p.name}</span><b>${state.lifetime[id].toLocaleString()}<em> GP</em></b></div><div class="body-meter"><i style="width:${Math.min(100,state.lifetime[id]/3)}%;background:${p.color}"></i></div></div>`).join('');
 $('station-cards').innerHTML=STATIONS.map((s,i)=>`<button class="exercise-card" data-station="${s.id}" ${walking?'disabled':''}><span class="exercise-icon">${icon(s.id)}</span><span><b>${s.name}</b><small>${PARTS[s.part].name} · 1회 +${reward(state,s.part)} GP</small></span><span>↗</span></button>`).join('');
 $('sound').innerHTML=icon(state.sound?'sound':'mute');$('sound').setAttribute('aria-label',state.sound?'소리 끄기':'소리 켜기');$('tree-dot').textContent=NODES.some(n=>unlocked(state,n)&&level(state,n.id)<n.max&&state.points>=price(state,n))?'·':'';
 if(active){$('rep-count').innerHTML=state.today[active.part]+'<span>REPS</span>';$('rep-reward').textContent=`1회 +${reward(state,active.part)} 포인트 · 체력 −${repCost(state)}`;$('exercise-weight').textContent=(active.weight*(level(state,active.part+'Load')?2:1))+' KG';}
 if(view==='tree')renderTree();if(scene)scene.state=state;
}
function nodeHTML(n){const lv=level(state,n.id),open=unlocked(state,n),max=lv>=n.max,can=open&&!max&&state.points>=price(state,n);return `<button class="node ${open?'':'locked'} ${lv?'owned':''} ${can?'available':''}" data-node="${n.id}" ${!can?'disabled':''} aria-label="${n.name}, ${n.desc}, ${!open?'선행 강화 필요':max?'강화 완료':price(state,n)+' 포인트'}"><span class="node-head">${icon(n.icon)}<small>${lv} / ${n.max}</small></span><b>${n.name}</b><p>${n.desc}</p><span class="node-price">${!open?'선행: '+n.requires.map(id=>NODES.find(x=>x.id===id).name).join(' · '):max?'강화 완료':price(state,n)+' GP'}</span></button>`;}
function renderTree(){const base=['stamina','efficiency','routine','form','tempo'];$('base-nodes').innerHTML=base.map(id=>nodeHTML(NODES.find(n=>n.id===id))).join('');$('branch-nodes').innerHTML=['chest','arms','legs'].map(part=>`<div class="branch">${NODES.filter(n=>n.branch===part).map(nodeHTML).join('')}</div>`).join('');$('master-node').innerHTML=nodeHTML(NODES.find(n=>n.id==='master'));}
function resetStroke(){pointer=null;cycle.reset();if(scene)scene.stroke=0;$('drag-handle').classList.remove('dragging');$('stroke-fill').style.height='0%';$('phase-hint').textContent=active?.id==='curl'?'덤벨을 잡고 위로 올려주세요':active?.id==='squat'?'손잡이를 올려 일어서 주세요':'바벨을 잡고 위로 올려주세요';}
function leave(){clearTimeout(exhaustTimer);active=null;walking=false;resetStroke();if(scene)scene.leave();$('workout').hidden=true;$('station-labels').hidden=false;$('rotate-view').hidden=false;render();}
function choose(id){if(!scene||walking||view!=='gym'||$('summary').open||$('help-dialog').open)return;if(state.energy<repCost(state)){showSummary();return;}const s=STATIONS.find(s=>s.id===id);if(!s)return;if(active?.id===id)return;if(active)leave();walking=true;$('station-labels').hidden=true;render();scene.walk(s,()=>{walking=false;active=s;scene.enter(s);$('workout').hidden=false;$('rotate-view').hidden=true;$('exercise-name').textContent=s.name;$('exercise-part').textContent=s.label+' TRAINING';resetStroke();render();});}
function switchView(next){if(walking)return;if(active)leave();view=next;$('tree-panel').hidden=next!=='tree';$('world').hidden=next==='tree';$('dashboard').hidden=next==='tree';$('gym-tab').classList.toggle('active',next==='gym');$('tree-tab').classList.toggle('active',next==='tree');render();if(next==='gym')scene?.resize();}
function showSummary(){if(walking)return;resetStroke();$('summary-day').textContent=`DAY ${String(state.day).padStart(2,'0')} · 총 ${Object.values(state.today).reduce((a,b)=>a+b,0)}회 운동`;$('summary-stats').innerHTML=Object.entries(PARTS).map(([id,p])=>`<div class="summary-row"><b>${p.name}</b><span>${state.today[id]}회</span><strong>+${state.lifetime[id]-state.dayStart[id]} GP</strong></div>`).join('');$('summary-earned').textContent=Object.keys(PARTS).reduce((n,p)=>n+state.lifetime[p]-state.dayStart[p],0)+' GP';$('cancel-rest').hidden=state.energy<repCost(state);if(!$('summary').open)$('summary').showModal();}
function stroke(value){if(!active||view!=='gym'||$('summary').open||$('help-dialog').open||state.energy<repCost(state))return;const valid=cycle.update(value,performance.now(),550*(1-.1*level(state,'tempo')));scene.stroke=cycle.value;$('stroke-fill').style.height=(cycle.value*100)+'%';$('phase-hint').textContent=cycle.peak?'좋아요! 이제 끝까지 내려주세요':'위로 끝까지 올려주세요';if(valid){const result=completeRep(state,active.part);if(!result)return;sound();scene.burst();const el=document.createElement('div');el.className='float-score';el.innerHTML=`+${result.points} GP<small>${PARTS[result.part].name} 성장</small>`;$('float-layer').append(el);setTimeout(()=>el.remove(),1500);$('phase-hint').textContent='좋아요! 한 번 더 해볼까요?';render();save();if(result.exhausted){toast('오늘의 운동 완료! 쉬면서 더 강해집니다.');exhaustTimer=setTimeout(showSummary,650);}}}
const handle=$('drag-handle');handle.addEventListener('pointerdown',e=>{if(pointer!==null||!active||state.energy<repCost(state))return;e.preventDefault();pointer=e.pointerId;handle.setPointerCapture(pointer);startY=e.clientY+scene.stroke*dragRange();handle.classList.add('dragging');});
function dragRange(){return Math.min(165,Math.max(105,scene.height*.29));}
handle.addEventListener('pointermove',e=>{if(e.pointerId!==pointer)return;e.preventDefault();stroke((startY-e.clientY)/dragRange());});
handle.addEventListener('pointerup',e=>{if(e.pointerId!==pointer)return;stroke((startY-e.clientY)/dragRange());if(handle.hasPointerCapture(e.pointerId))handle.releasePointerCapture(e.pointerId);resetStroke();});handle.addEventListener('pointercancel',resetStroke);handle.addEventListener('lostpointercapture',()=>{if(pointer!==null)resetStroke();});
window.addEventListener('keydown',e=>{if(!$('summary').open&&!$('help-dialog').open&&active&&['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();stroke(scene.stroke+(e.key==='ArrowUp'?.12:-.12));}if(e.key==='Escape'&&!$('summary').open&&!$('help-dialog').open&&active)leave();});window.addEventListener('blur',resetStroke);document.addEventListener('visibilitychange',()=>{if(document.hidden){resetStroke();save();}});
$('station-cards').addEventListener('click',e=>{const b=e.target.closest('[data-station]');if(b)choose(b.dataset.station);});$('station-labels').addEventListener('click',e=>{const b=e.target.closest('[data-station]');if(b)choose(b.dataset.station);});$('leave').onclick=leave;$('rest').onclick=showSummary;$('cancel-rest').onclick=()=>$('summary').close();$('next-day').onclick=()=>{$('summary').close();leave();nextDay(state);render();save();toast(`DAY ${state.day} · 체력을 모두 회복했어요.`);};
$('gym-tab').onclick=()=>switchView('gym');$('tree-tab').onclick=()=>switchView('tree');$('return-gym').onclick=()=>switchView('gym');document.querySelector('.brand').onclick=e=>{e.preventDefault();switchView('gym');};
$('tree-panel').addEventListener('click',e=>{const b=e.target.closest('[data-node]');if(!b)return;const n=NODES.find(n=>n.id===b.dataset.node);if(buyNode(state,n.id)){sound('buy');render();save();toast(n.name+' 강화 완료');}});
$('sound').onclick=()=>{state.sound=!state.sound;render();save();};$('help').onclick=()=>{resetStroke();$('help-dialog').showModal();};$('close-help').onclick=()=>$('help-dialog').close();$('reset').onclick=()=>$('reset-confirm').hidden=false;$('reset-no').onclick=()=>$('reset-confirm').hidden=true;$('reset-yes').onclick=()=>{clearTimeout(exhaustTimer);state=freshState();leave();switchView('gym');$('reset-confirm').hidden=true;$('help-dialog').close();save();render();toast('새로운 첫날을 시작합니다.');};$('rotate-view').onclick=()=>scene.cameraMode=1-scene.cameraMode;
try{scene=new GymScene($('scene'),choose);scene.state=state;$('loading').hidden=true;$('station-labels').innerHTML=STATIONS.map((s,i)=>`<button class="station-label" data-station="${s.id}"><small>0${i+1}</small>${s.name}<span>↗</span></button>`).join('');scene.onFrame=()=>{if(view!=='gym')return;for(const s of STATIONS){const p=scene.projectPoint(s.x,.2,s.z+2.5);const el=document.querySelector(`.station-label[data-station="${s.id}"]`);el.style.left=p.x+'px';el.style.top=p.y+'px';}if(active){const p=scene.handlePosition();handle.style.left=p.x+'px';handle.style.top=p.y+'px';}};}catch(error){console.error(error);$('loading').innerHTML='<div style="text-align:center;padding:30px"><b>3D 화면을 시작할 수 없습니다.</b><p>WebGL을 지원하는 Chrome 또는 Edge에서 다시 열어주세요.</p></div>';}
render();save();
